services:
  - type: web
    name: agriturismo-rosita
    env: static
    staticPublishPath: agriturismorosita
    buildCommand: ""
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /images/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /
        destination: /index.html
